---
- hosts: My_Group
  become: yes
- name: Installing java11
  include: installJava11.yaml
- name: installDocker
  include: installDocker.yaml
- name: installPython3Docker
  include: installPython3Docker.yaml
- name: createJenkinsImage
  include: createJenkinsImage.yaml
- name: createContainerWithJenkins
  include: createContainerWithJenkins.yaml