---
- hosts: My_Group
  become: yes
  tasks:
    - name: create a container from ther jenkins docker image
      docker_container:
        name: "jenkins"
        image: "jenkins:2.60.3-alpine"
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - "/share/jenkins:/var/jenkins_home"
        state: started
        detach: yes